name: android-release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: platform/android
    env:
      JOBS: 8
      BUILDTYPE: Release
      IS_LOCAL_DEVELOPMENT: false
    steps:

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: npm install
        run: npm install --ignore-scripts          
        working-directory: platform/android

      - name: Install ccache
        run: sudo apt-get install -y ccache

      - name: Prepare ccache
        run: ccache --clear       

      - name: Cache ccache
        uses: actions/cache@v3
        env:
          cache-name: ccache-v1     
        with:
          path: ~/.ccache'
          key: ${{ env.cache-name }}-${{ runner.os }}-${{ github.job }}-${{ github.ref }}-${{ github.sha }}-${{ github.head_ref }}
          restore-keys: |
            ${{ env.cache-name }}-${{ runner.os }}-${{ github.job }}-${{ github.ref }}-${{ github.sha }}
            ${{ env.cache-name }}-${{ runner.os }}-${{ github.job }}-${{ github.ref }}
            ${{ env.cache-name }}-${{ runner.os }}-${{ github.job }}  

      - name: Clear ccache statistics
        run: |
          ccache --zero-stats
          ccache --max-size=2G
          ccache --show-stats   

      - name: restore-gradle-cache
        uses: actions/cache@v3
        env:
          cache-name: gradle-v1
        with:
          path: ~/.gradle'     
          key: ${{ env.cache-name }}-{{ hashFiles 'gradle/dependencies.gradle' }}-{{ hashFiles 'build.gradle' }}-{{ hashFiles 'gradle/wrapper/gradle-wrapper.properties' }}'
          restore-keys: |
            - ${{ env.cache-name }}   

      - name: Android nitpick
        run: make run-android-nitpick
        
      - name: Update version name
        run: |
          RELEASE_VERSION="$( git describe --tags --match=android-v*.*.* --abbrev=0 | sed 's/^android-v//' )"
          echo "Latest version from tag: $RELEASE_VERSION"
          if [ ! -z "$RELEASE_VERSION" ]; then
            sed -i -e "s/^VERSION_NAME=.*/VERSION_NAME=${RELEASE_VERSION}/" MapboxGLAndroidSDK/gradle.properties
            echo "MapboxGLAndroidSDK/gradle.properties:"
            cat MapboxGLAndroidSDK/gradle.properties
          fi
        shell: bash

      - name: Build package
        run: make apackage

      - name: Build release Test App
        run: |
          MAPLIBRE_DEVELOPER_CONFIG_XML='${{ secrets.MAPLIBRE_DEVELOPER_CONFIG_XML }}'
          if [ -n "${MAPLIBRE_DEVELOPER_CONFIG_XML}" ]; then
            echo "${MAPLIBRE_DEVELOPER_CONFIG_XML}" > MapboxGLAndroidSDKTestApp/src/main/res/values/developer-config.xml
            make android
          else
            echo "No secrets.MAPLIBRE_DEVELOPER_CONFIG_XML variable set, skipping apk build..."
          fi
        shell: bash
      
      - name: Upload aar
        id: upload-release-asset 
        uses: actions/upload-artifact@v3
        with:
          name: release-aar
          path: platform/android/MapboxGLAndroidSDK/build/outputs/aar/MapboxGLAndroidSDK-release.aar
          retention-days: 14
